"""Playbook config package (split from playbook_config.py)."""
from __future__ import annotations

from playbooks.config.constants import (
    CONFIG_KEY,
    _VALID_PROBE_PRIORITIES,
    CANONICAL_ORACLE_TYPES,
    DETERMINISTIC_ORACLE_TYPES,
    _VALID_TOOL_ORACLE_FLAGS,
    CANONICAL_ADAPTIVE_SEED_GUIDANCE,
    OBJECTIVE_LEXICON_MAX_KEYS,
    OBJECTIVE_LEXICON_KEY_RE,
    OBJECTIVE_LEXICON_TOKEN_RE,
    ENHANCEMENT_THESIS_VALUES,
    CANONICAL_DELIVERY_PROMPT_RULES,
    _VALID_DELIVERY_TRANSFORM_MODES,
    _VALID_DELIVERY_TRANSFORM_KINDS,
    _META_LEAKAGE_NEEDLES,
    _DETECTION_FLOOR_GUIDANCE_RE,
    _strategy_is_adaptive,
    _as_dict,
    _truncate,
    _delivery_from_play_prose,
    _distinctive_content_words,
    _batch_keep_floor,
    _nonempty_directive_strings,
)

from playbooks.config.accessors import (
    normalized_playbook_config,
    get_playbook_config,
    get_adaptive_section,
    get_recon_section,
    get_generation_section,
    get_enhancement_section,
    get_assessment_section,
    get_assessment_oracles,
    apply_delivery_to_seeds,
    get_generation_mandatory_directives,
    get_escalation_payload,
    get_escalation_payload_expanded,
    get_delivery_transforms,
    prompt_embeds_phrase,
    row_prompt_blob,
    prompt_embeds_attack_objective,
    filter_prompts_missing_attack_objective,
    prompt_has_meta_leakage,
    filter_prompts_meta_leakage,
    prompt_embeds_escalation_payload,
    filter_prompts_embedding_escalation_payload,
    _derived_delivery_prompt_rules,
    get_prompt_requirement_rules,
    _normalize_prompt_rules,
    prompt_meets_playbook_requirements,
    get_adaptive_delivery_constraints,
    get_adaptive_seed_guidance,
    _coerce_mandatory_directives,
    _coerce_int_field,
    _coerce_probe_hints,
    _coerce_enhancement_thesis,
    _coerce_delivery_transforms,
    canonicalize_playbook_config_storage,
    get_adaptive_followup_guidance,
    get_adaptive_runtime_limits,
    _strategy_seed_guidance,
    get_generation_expert_guidance,
    get_enhancement_theory_guidance,
    _playbook_family_prefix,
    get_enhancement_thesis,
    get_recon_probe_hints,
)

from playbooks.config.lexicon import (
    get_attack_objective,
    normalize_objective_text,
    normalize_objective_lexicon,
    get_objective_lexicon,
    expand_lexicon_text,
    wrap_bare_lexicon_keys,
    get_attack_objective_expanded,
    canonicalize_attack_objective_tokens,
    expand_prompt_row_lexicon,
    expand_prompts_lexicon,
    expand_lexicon_in_value,
)

from playbooks.config.prompt_template import (
    get_prompt_template,
    get_prompt_task,
    get_prompt_format,
    prompt_template_has_input_slot,
    normalize_prompt_template_fields,
    apply_prompt_template,
    apply_prompt_row_template,
    apply_prompts_template,
)

from playbooks.config.phase1_escalate import (
    is_meta_escalation_payload,
    is_weak_escalation_payload,
    is_status_banner_escalation_payload,
    _phase1_content_tokens,
    escalate_signature_ngrams,
    _prose_has_token_ngram,
    _escalate_high_signal_markers,
    phase1_embeds_escalation_payload,
    phase1_has_escalation_negation_bait,
    sanitize_phase1_text_against_escalation,
    sanitize_phase1_escalation_embeds,
    is_meta_attack_objective,
    has_measurable_phase1_ask,
    leaf_catalog_asset_blob,
    attack_objective_names_leaf_asset,
    iter_phase1_guidance_fields,
    _critical_treats_canary_as_full_success,
    canary_critical_with_escalation_errors,
    escalation_payload_weaker_than_phase1,
    strengthen_weak_escalation_payload,
    escalation_critical_alignment_errors,
    prose_cites_escalation_payload_key,
    neutralize_escalation_key_citations,
    _escalation_key_prose_error,
)

from playbooks.config.techniques import (
    _load_get_techniques,
    _technique_pack_names,
    pack_has_detection_floor_technique,
    best_technique_anchor_for_text,
    category_mechanism_distinctness_errors,
    playbook_has_detection_floor_guidance,
)

from playbooks.config.formatters import (
    format_attack_objective_override,
    format_attack_objective_block,
    format_mandatory_generation_block,
    format_judge_delivery_gate,
    format_strategy_seed_guidance,
    format_generation_expert_block,
    format_enhancement_thesis_theory_rail,
    format_enhancement_thesis_assess_note,
    format_adaptive_operational_block,
)

from playbooks.config.validate import (
    validate_playbook_config,
)

__all__ = ['CANONICAL_ADAPTIVE_SEED_GUIDANCE', 'CANONICAL_DELIVERY_PROMPT_RULES', 'CANONICAL_ORACLE_TYPES', 'CONFIG_KEY', 'DETERMINISTIC_ORACLE_TYPES', 'ENHANCEMENT_THESIS_VALUES', 'OBJECTIVE_LEXICON_KEY_RE', 'OBJECTIVE_LEXICON_MAX_KEYS', 'OBJECTIVE_LEXICON_TOKEN_RE', '_DETECTION_FLOOR_GUIDANCE_RE', '_META_LEAKAGE_NEEDLES', '_VALID_DELIVERY_TRANSFORM_KINDS', '_VALID_DELIVERY_TRANSFORM_MODES', '_VALID_PROBE_PRIORITIES', '_VALID_TOOL_ORACLE_FLAGS', '_as_dict', '_batch_keep_floor', '_coerce_delivery_transforms', '_coerce_enhancement_thesis', '_coerce_int_field', '_coerce_mandatory_directives', '_coerce_probe_hints', '_critical_treats_canary_as_full_success', '_delivery_from_play_prose', '_derived_delivery_prompt_rules', '_distinctive_content_words', '_escalate_high_signal_markers', '_escalation_key_prose_error', '_load_get_techniques', '_nonempty_directive_strings', '_normalize_prompt_rules', '_phase1_content_tokens', '_playbook_family_prefix', '_prose_has_token_ngram', '_strategy_is_adaptive', '_strategy_seed_guidance', '_technique_pack_names', '_truncate', 'apply_delivery_to_seeds', 'apply_prompt_row_template', 'apply_prompt_template', 'apply_prompts_template', 'attack_objective_names_leaf_asset', 'best_technique_anchor_for_text', 'canary_critical_with_escalation_errors', 'canonicalize_attack_objective_tokens', 'canonicalize_playbook_config_storage', 'category_mechanism_distinctness_errors', 'escalate_signature_ngrams', 'escalation_critical_alignment_errors', 'escalation_payload_weaker_than_phase1', 'expand_lexicon_in_value', 'expand_lexicon_text', 'expand_prompt_row_lexicon', 'expand_prompts_lexicon', 'filter_prompts_embedding_escalation_payload', 'filter_prompts_meta_leakage', 'filter_prompts_missing_attack_objective', 'format_adaptive_operational_block', 'format_attack_objective_block', 'format_attack_objective_override', 'format_enhancement_thesis_assess_note', 'format_enhancement_thesis_theory_rail', 'format_generation_expert_block', 'format_judge_delivery_gate', 'format_mandatory_generation_block', 'format_strategy_seed_guidance', 'get_adaptive_delivery_constraints', 'get_adaptive_followup_guidance', 'get_adaptive_runtime_limits', 'get_adaptive_section', 'get_adaptive_seed_guidance', 'get_assessment_oracles', 'get_assessment_section', 'get_attack_objective', 'get_attack_objective_expanded', 'get_delivery_transforms', 'get_enhancement_section', 'get_enhancement_theory_guidance', 'get_enhancement_thesis', 'get_escalation_payload', 'get_escalation_payload_expanded', 'get_generation_expert_guidance', 'get_generation_mandatory_directives', 'get_generation_section', 'get_objective_lexicon', 'get_playbook_config', 'get_prompt_format', 'get_prompt_requirement_rules', 'get_prompt_task', 'get_prompt_template', 'get_recon_probe_hints', 'get_recon_section', 'has_measurable_phase1_ask', 'is_meta_attack_objective', 'is_meta_escalation_payload', 'is_status_banner_escalation_payload', 'is_weak_escalation_payload', 'iter_phase1_guidance_fields', 'leaf_catalog_asset_blob', 'neutralize_escalation_key_citations', 'normalize_objective_lexicon', 'normalize_objective_text', 'normalize_prompt_template_fields', 'normalized_playbook_config', 'pack_has_detection_floor_technique', 'phase1_embeds_escalation_payload', 'phase1_has_escalation_negation_bait', 'playbook_has_detection_floor_guidance', 'prompt_embeds_attack_objective', 'prompt_embeds_escalation_payload', 'prompt_embeds_phrase', 'prompt_has_meta_leakage', 'prompt_meets_playbook_requirements', 'prompt_template_has_input_slot', 'prose_cites_escalation_payload_key', 'row_prompt_blob', 'sanitize_phase1_escalation_embeds', 'sanitize_phase1_text_against_escalation', 'strengthen_weak_escalation_payload', 'validate_playbook_config', 'wrap_bare_lexicon_keys']
